[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
Fusion = "3b20d082-0f76-48e4-9f8b-58c09b1136ea"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
